trigger: none

stages:
# Stage 1: Check and Start VM
- stage: CheckVM
  jobs:
  - job: StartVM
    pool:
      name: Default

    steps:
    - powershell: |
        Write-Host "Controller Agent: $env:COMPUTERNAME"

        $vmName = "$(VM_NAME)"
        $rg = "$(RESOURCE_GROUP)"

        Write-Host "VM: $vmName"
        Write-Host "RG: $rg"

        if (-not $vmName -or -not $rg) {
          Write-Error "VM_NAME or RESOURCE_GROUP not set"
          exit 1
        }

        az login --service-principal --username $env:AZURE_CLIENT_ID --password="$env:AZURE_CLIENT_SECRET" --tenant $env:AZURE_TENANT_ID
        az account set --subscription $env:AZURE_SUBSCRIPTION_ID

        $status = az vm get-instance-view --name $vmName --resource-group $rg --query "instanceView.statuses[1].displayStatus" -o tsv

        Write-Host "Current Status: $status"

        if ($status -ne "VM running") {
          Write-Host "Starting VM..."
          az vm start --name $vmName --resource-group $rg --no-wait
        } else {
          Write-Host "VM already running."
        }

        Start-Sleep -Seconds 120

      env:
        AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
        AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
        AZURE_TENANT_ID: $(AZURE_TENANT_ID)
        AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)


# Stage 2: Main workload for build and deploy
- stage: RunPipeline
  dependsOn: CheckVM
  jobs:
  - job: Run
    pool:
      name: SHA

    steps:
    - powershell: |
        Write-Host "Worker Agent: $env:COMPUTERNAME"

# Stage 3: Send shutdown signal o the VM
- stage: ShutdownVM
  dependsOn: RunPipeline
  condition: always()

  jobs:
  - job: StopVM
    pool:
      name: Default

    steps:
    - powershell: |
        az login --service-principal --username $env:AZURE_CLIENT_ID --password="$env:AZURE_CLIENT_SECRET" --tenant $env:AZURE_TENANT_ID
        az account set --subscription $env:AZURE_SUBSCRIPTION_ID

        az vm deallocate --name "$(VM_NAME)" --resource-group "$(RESOURCE_GROUP)"

      env:
        AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
        AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
        AZURE_TENANT_ID: $(AZURE_TENANT_ID)
        AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
